---
#
# general config values
#
awscli:
  pypi:
    version: &awscli_ver '1.14.61'
  dockerfile:
    github_repo: lsst-sqre/docker-awscli
    git_ref: master
    dir: ''
  docker_registry:
    repo: lsstsqre/awscli
    tag: *awscli_ver
codekit:
  pypi:
    version: &codekit_ver '7.4.1'
  dockerfile:
    github_repo: lsst-sqre/sqre-codekit
    git_ref: master
    dir: docker
  docker_registry:
    repo: lsstsqre/codekit
    tag: *codekit_ver
dind:
  dockerfile:
    github_repo: lsst-sqre/docker-dind
    git_ref: master
    dir: ''
  docker_registry:
    repo: provinggroundcurly/dind
    tag: '18.09.5'
s3sync:
  dockerfile:
    github_repo: lsst-sqre/deploy-publish-release
    git_ref: master
    dir: s3sync
  docker_registry:
    repo: lsstsqre/s3sync
    tag: latest
eupsredirector:
  dockerfile:
    github_repo: lsst-sqre/terraform-pkgroot-redirect
    git_ref: master
    dir: eupsredirector
  docker_registry:
    repo: lsstsqre/eupsredirector
    tag: latest
cmirror:
  docker_registry:
    repo: lsstsqre/cmirror
    tag: latest
wget:
  docker_registry:
    repo: lsstsqre/wget
    tag: latest
squash:
  url: https://squash-restful-api-demo.lsst.codes/
layercake:
  packer:
    github_repo: lsst-sqre/packer-layercake
    git_ref: master
    dir: ''
  docker_registry:
    repo: lsstsqre/centos
